# Generated by Django 5.0.2 on 2024-02-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Proffiller'},
        ),
        migrations.AlterModelOptions(
            name='profilestatus',
            options={'verbose_name_plural': 'Profil Durumları'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles_photo/%Y/%m/'),
        ),
    ]
